defaults:
# ========model========
    - model:  scmbm
# ========prerpocessing========
    - preprocess:  base
# ========dataset========
dataset:
    - train:
        - drama: sbj_1-session_all
    - val:
        - god: sbj_1-train-session_6_12
dataset_yaml:
    - drama: drama_vc.yaml # drama_config.yaml # region 160 ch
    - god: god_vc.yaml # god_config.yaml
total_limit: 1000 # num_trials

# ========path========
logdir: 'logdir'
ckpt_dir: 'ckpt_dir'
h5_root: 'h5_root'


# ========training========
precision: 16
val_check_interval: 1
num_workers: 4
batch_size: 100
lr: 2.5e-4
min_lr: 0
weight_decay: 0.05
num_epoch: 500
wqrmup_epochs: 40
clip_grad: 0.8
