# ========model========
meg_encoder:  scmbm
image_encoder: vit_clip16
decoder: mapping
# ========prerpocessing========
preprocess: base

# ========dataset========
dataset_name:
    train:
        # drama: sbj_1-session_all # all 1_3, 1~3
        GOD: sbj_1-train-session_1_2_3_4_5_7_8_9_10_11
    val:
        GOD: sbj_1-train-session_6_12
dataset_yaml:
    # drama: drama/drama_vc.yaml # drama_config.yaml # region 160 ch
    GOD: GOD/god_vc.yaml # god_config.yaml
total_limit:
    train:
        GOD: 6000
        # drama: 6000 # total number of samples across sessions about: 31200
    val:
        GOD: 1200 # total number of samples across sessions

# ========path========
h5_root: ../../../dataset/ssl_dataset/{h5_name}
resume_path: null
meg_encoder_path: '../../results_ssl/{exp_name}/ckpt/best.pth' #
image_encoder_path: null # null is allowed

# ========training========
training:
    val_check_interval: 10
    num_workers: 4 # 4
    batch_size: 5
    lr: 5.3e-5
    min_lr: 0
    weight_decay: 0.05
    num_epoch: 500
    warmup_epochs: 40
    # clip_grad: 0.8
    accum_iter: 1
    # ========dream diffusion========
    img_size: 512
    precision: 32
    accumulate_grad: 1
    crop_ratio: 0.2
    global_pool: False
    use_time_cond: True
    clip_tune: True #False
    cls_tune: False
    eval_avg: True
    num_samples: 5
    ddim_steps: 250
    HW: null
    model_meta: null
    checkpoint_path: null
    allow_full_validation: False

    logdir: '../../results_task/dream_diffusion/{exp_name}/log'
    ckpt_dir: '../../results_task/dream_diffusion/{exp_name}/ckpt'
    reconst_dir: '../../results_task/dream_diffusion/{exp_name}/reconst'
    # ========fine-tuning========
    meg_encoder_finetune: none
    image_encoder_finetune: none
    # ========criterion========
    criterion: MSE
    # ========CLIP LOSS=======
    clip:
        reduction: 'mean'
        init_temperature: 5.1


root_path: '../../results_task/dream_diffusion/'
output_path: '../../results_task/dream_diffusion/{exp_name}/'

