name: GOD
# =====Path settings======
kernel_root: /work/project/MEG_GOD/GOD_dataset
ch_region_path: './data/GOD/ch_region.json'
montage_path: './data/GOD/montage.csv'
bdata_path: '/work/project/MEG_GOD/hyang/BData/ROI/hcp44_{block_id}.mat'
# ======Spatial Region settings======
roi_block_ids: null # [1, 2, 3, 4, 5, 24, 25, 26, 27, 28] # ROI (HCP atlas): V1 + early visual + ventral stream + MT+ complex and neighboring
region:
  - occipital/left
  - occipital/right
  - frontal/left
  - frontal/right
  - temporal/left
  - temporal/right
  - parietal/left
  - parietal/right
  - central/left
  - central/right
# ======Fs settings======
meg_fs: 1000