# ========model========
image_encoder: vit_clip16
## brain encoder
window:
  start: 0.2 # [s]
  end: 0.4 # [s]
preprocs:
  brain_resample_rate: 120 # 1000 # Hz
  baseline_len_sec: 0
  brain_filter: [2,5] #[1.0, 60] # null is allowed
  last4layers: False       # if True, the brain_encoder's emsize will be 1024, not 512
  # subject_wise: True       # whether to scale each subject's EEG dataset individually (only for Brennan2018)
  clamp: True
  clamp_lim: 20
region:
  - occipital/left
  - occipital/right
  # - frontal/left
  # - frontal/right
  # - temporal/left
  # - temporal/right
  # - parietal/left
  # - parietal/right
  # - central/left
  # - central/right 
ch_region_path: './data/GOD/ch_region.json'
montage_path: './data/GOD/montage.csv'
# ========prerpocessing========
preprocess: fs120_dura200

# ========dataset========
dataset_name:
    train:
        drama: sbj_1-session_all #all # all 1_3, 1~3
        GOD: sbj_1-train-session_1_2_3_4_5_7_8_9_10_11
    val:
        GOD: sbj_1-train-session_6_12
dataset_yaml:
    drama: drama/drama_vc.yaml # region 160 ch
    GOD: GOD/god_vc.yaml
total_limit:
    train:
        GOD: 6000
        drama: 12000 # total number of samples across sessions about: 31200
    val:
        GOD: 1200 # total number of samples across sessions

# ========path========
h5_root: ../../../dataset/ssl_dataset/sbj1/regression
image_encoder_path: null # null is allowed
save_root: '/home/yainoue/meg2image/results/20230926_sbj01_eegnet_cv_norm_regression_drama'

# ===== Training settings ====
use_wandb: false
reproducible: true
use_sampler: false
z_scoring: true
rest_duration: 60
num_workers: 8
batch_size: 256 # original: 64, paper: 128
updates: 200
lr: 3e-4
lr_scheduler: none # cosine or multistep or none
lr_multistep_mlstns: [0.4, 0.6, 0.8, 0.9]
lr_step_gamma: 0.5
epochs: 300
reduction: mean

# ==== Architecture ==== #
model: eegnet
k1: 10 # 960
k2: 4 # 96
F1: 16
F2: 32
D: 2
# p0: 10
p1: 2 # 40
p2: 4 # 80
dr1: 0.50
dr2: 0.75
# for EEGNet_Multi
n_head: 8
dim_per_head: 64
fc1: 256
fc2: 128
# num_channels: 22

init_temperature: 5.1
temp_trainable: true
criterion: crossentropy

normalize_image_features: True
normalize_meg : True
memory_efficient: True
channel_size: null # dummy not use