defaults:
# ========model========
    - model:  scmbm
# ========prerpocessing========
    - preprocess:  base
# ========dataset========
dataset_name:
    train:
        drama: sbj_1-session_1~3 # all 1_3, 1~3
    val:
        GOD: sbj_1-train-session_6_12
dataset_yaml:
    drama: drama/drama_vc.yaml # drama_config.yaml # region 160 ch
    GOD: GOD/god_vc.yaml # god_config.yaml
total_limit:
    train:
        drama: 1000 # total number of samples across sessions
    val:
        GOD: 1200 # total number of samples across sessions

# ========path========
logdir: '../../results_ssl/test/log'
ckpt_dir: '../../results_ssl/test/ckpt'
reconst_fig_dir: '../../results_ssl/test/reconst_fig'
h5_root: ../../../dataset/ssl_dataset/test
resume_path: null

# ========training========
precision: 16
val_check_interval: 1
num_workers: 4
batch_size: 100
lr: 2.5e-4
min_lr: 0
weight_decay: 0.05
num_epoch: 500
wqrmup_epochs: 40
clip_grad: 0.8
